### ISSUE TITLE
Feature Request Record Audio Pause Resume

### ISSUE THREAD

**Issue by indiascope** [Arjun-sna/Android-AudioRecorder-App#2]
Hi,

In Audio record you can add pause resume functionality ? currently after pause audio always start new audio recording you can add additional functionality like continuous audio recording after pause user can resume audio and again start recording .Again thanks for great library for record audio in background.

**Comment by Arjun-sna** [comment]
Hi,
The pause resume functionality is already there in the current release and it is also working as expected. It will resume recording from the point where it is paused.

**Comment by indiascope** [comment]
Thanks for reply. yes i found it.check Demo app and found Resume,Pause Functionality. Again thanks for great library.
